### ISSUE TITLE
--load-and-launch-app= doesn't work?

### ISSUE THREAD

**Issue by ismetisc** [Ceiridge/Chrome-Developer-Mode-Extension-Warning-Patcher#10]
hello when i am trying to load extension chrome start with this --load-and-launch-app="C:\Users\maho\ex"

but the extension is not load why?

Can you help me please?

Thanks.

**Comment by Ceiridge** [comment]
- ### _it looks like you have trooo much thermal paste on your cprocesor_

- [ ] **please remove all of the paste from your cpu and try again**
