### ISSUE TITLE
How to uninstall this program?

### ISSUE THREAD

**Issue by fchagas97** [Ceiridge/Chrome-Developer-Mode-Extension-Warning-Patcher#101]
I want to uninstall the program, I no longer remember why I installed it.
I can't find the ChromeDevExtWarningPatcher.exe executable in the C:\Program Files\Ceiridge\ChromeDllInjector folder

**Comment by Ceiridge** [comment]
The program can be fully uninstalled with the installer that can be downloaded in the Releases section on this repository.
If you have a very old version, make sure to download the appropriate installer.
In the installer, there is an uninstall button

**Comment by fchagas97** [comment]
I found it in #80, sorry for my lazy ass not looking in the closed issues too 🤦🏻‍♂️
