### ISSUE TITLE
Commandline options without CustomPath give null exception

### ISSUE THREAD

**Issue by kababoom** [Ceiridge/Chrome-Developer-Mode-Extension-Warning-Patcher#12]
Perhaps change line 52:

if(clOptions.CustomPath != null) 

Cheers,
-M

**Comment by Ceiridge** [comment]
41b8ecd0ffe1edb2f44e29468b3e80ce0fcdeef8
https://github.com/Ceiridge/Chrome-Developer-Mode-Extension-Warning-Patcher/releases/tag/3.4

**Comment by kababoom** [comment]
Awesome :-)
