### ISSUE TITLE
Request: chrome crashed, restore warning patch

### ISSUE THREAD

**Issue by kababoom** [Ceiridge/Chrome-Developer-Mode-Extension-Warning-Patcher#13]
Curious if it is possible to remove this pop-up too?

It's a warning after crashing, other option is to change ~/.config/chromium/Default/Preferences and set "exit_type": "Normal" and "exited_cleanly": true before each start.
But patching is much cooler :-)

Thanks again,
-M

**Comment by Ceiridge** [comment]
Yes, that's also possible

**Comment by Ceiridge** [comment]
ea57caee84efac5753baa2b186924695c5e2c284
https://github.com/Ceiridge/Chrome-Developer-Mode-Extension-Warning-Patcher/releases/tag/3.5
