### ISSUE TITLE
Code missing referenced CommandLine Project

### ISSUE THREAD

**Issue by GarethWright** [Ceiridge/Chrome-Developer-Mode-Extension-Warning-Patcher#14]
As per title

**Comment by GarethWright** [comment]
Ignore me....silly mistake.

DElete the project and run Install-Package CommandLineParser -Version 2.7.82

**Comment by Ceiridge** [comment]
You should have cloned it with `git clone --recursive https://github.com/Ceiridge/Chrome-Developer-Mode-Extension-Warning-Patcher.git`, so that the submodules are downloaded, too
