### ISSUE TITLE
Issue with Brave 81.1.8.86

### ISSUE THREAD

**Issue by TirOFlanc** [Ceiridge/Chrome-Developer-Mode-Extension-Warning-Patcher#15]
Hello,

There is a problem with the latest version of Brave to disable the alert for extensions in developer mode.

```
C:\ChromeDevExtWarningPatcher.exe --cust
omPath "C:\Program Files (x86)\BraveSoftware\Brave-Browser\Application" --disabl
eGroups 1,2 --noWait

Found pattern offset at 73424958
Source byte of patch at 22: 4
73424980 => 255
Found pattern offset at 73424958
Source byte of patch at 35: 8
73424993 => 255
Couldn't find offset for a patch Remove Crash Warning
Error trying to patch C:\Program Files (x86)\BraveSoftware\Brave-Browser\Applica
tion\81.1.8.86\chrome.dll
```

Made with version 3.6 of ChromeDevExtWarningPatcher

Have a nice day :)

**Comment by Ceiridge** [comment]
You've enabled "Remove Crash Warning".
Tell me what you can read when you hover over the patch with your mouse.

**Comment by Ceiridge** [comment]
I just saw that you were using the command line. There is a new patch group 3 that is "Remove Crash Warning".
I should add an argument _--onlyGroups_, because it is affected by new patches in the patterns.xml file.

**Comment by TirOFlanc** [comment]
Oh yes !
"This patch removes the warning after a chromium crash (doesn't work for some browsers like Brave)"
Next time, I'll think about checking the GUI.
So I need to add 3 to --disableGroups or just wait your next version with the new arg ?

**Comment by Ceiridge** [comment]
You can wait for the new version with the new arg, because it doesn't make sense to always break the tool after a new update.
It should be released in 15 minutes

**Comment by TirOFlanc** [comment]
Oh, it's not that hurry but ok, you're so responsive. ^^'

**Comment by Ceiridge** [comment]
ec600877680adad6554ba615cd63a8870da66524
https://github.com/Ceiridge/Chrome-Developer-Mode-Extension-Warning-Patcher/releases/tag/3.7

**Comment by TirOFlanc** [comment]
It's Works fine !

For people who just want to disable the brave's dev ext warning :

ChromeDevExtWarningPatcher.exe --customPath "C:\Program Files (x86)\BraveSoftware\Brave-Browser\Application" --groups 0 --noWait

Thank you very much.
