### ISSUE TITLE
i have some  some problems here,

### ISSUE THREAD

**Issue by jiurou** [Ceiridge/Chrome-Developer-Mode-Extension-Warning-Patcher#17]
![image](https://user-images.githubusercontent.com/51284164/81362321-25a1fa80-9113-11ea-8f60-1b900c892847.png)

**Comment by Ceiridge** [comment]
This means that the patcher wasn't able to get the patterns.xml file? Are you living in the PR China and maybe Github is blocked by the Chinese firewall?

**Comment by jiurou** [comment]
But I can browse this page ？You mean unable to connect to server in the picture？
Thanks！

**Comment by Ceiridge** [comment]
All I can tell you is that it wasn't able to connect to githubusercontent.com, a github domain.
What you can do is to cache the file manually:

1. Download the patterns.xml: https://raw.githubusercontent.com/Ceiridge/Chrome-Developer-Mode-Extension-Warning-Patcher/master/patterns.xml
2. Rename it to `chrome_patcher_patterns.xml`
3. Move this file to your %temp% folder. Example: `C:\Users\YOURUSER\AppData\Local\Temp\chrome_patcher_patterns.xml`

But keep in mind that if you do this, you won't get any auto-updates, but you can always just download the file again.

**Comment by jiurou** [comment]
Done！You are awesome！
