### ISSUE TITLE
Ceased to work with New Edge Update to v83.0.478.37

### ISSUE THREAD

**Issue by rh63** [Ceiridge/Chrome-Developer-Mode-Extension-Warning-Patcher#18]
Since it is not possible to copy the Log Output, here you go:

![Clip](https://user-images.githubusercontent.com/65854998/82754165-6e240e00-9dcb-11ea-8847-f90184aff6e1.png)

BTW: Could you **PLEASE** change that awful coloring? The text is nearly unreadable in dark red on dark grey...

Thanks for creating this tool! :)

**Comment by Ceiridge** [comment]
2a03c9436b853dce779d03ec404fcac63da528b6
3afd838a2e5d3c5b3b89cb213824ad3a87d631eb
b7cb658a4a179c67b2866a073fa6f94172a202e9
1bf642339836688768f5e892568a3936e83bc2a7
https://github.com/Ceiridge/Chrome-Developer-Mode-Extension-Warning-Patcher/releases/tag/3.9

**Comment by rh63** [comment]
Thank you for the quick release! :)
Works perfectly now.
