### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by oleedd** [Ceiridge/Chrome-Developer-Mode-Extension-Warning-Patcher#20]
What versions are supported?
It doesn't work for Chrome 65 Portable (64 bit).  It gives "`Couldn't find offset for a patch Remove Extension Warning`" error.
The dll file:
[chrome.dll.zip](https://github.com/Ceiridge/Chrome-Developer-Mode-Extension-Warning-Patcher/files/4753547/chrome.dll.zip)
Please fix.

**Comment by Ceiridge** [comment]
Such old versions are not supported and you can probably find a flag in chrome://flags to fix it.
Besides that, you can try to use another patch that I once found some years ago. I think it was somewhere on StackOverflow.

The versions 79-83 have been tested and worked, but only the latest Chrome version is supported.

**Comment by Ceiridge** [comment]
This could also work: https://stackoverflow.com/questions/23055651/disable-developer-mode-extensions-pop-up-in-chrome/38011386#38011386

**Comment by oleedd** [comment]
I saw this before. It didn't help and caused problems with PC.
Another patch works with much older (ancient) versions.
Can you please give the signature or an address (using the uploaded dll) where I should change values? I tried to find - but no success.

**Comment by Ceiridge** [comment]
No, because I would need to find it in the old version, which would take about 15-60 minutes

**Comment by oleedd** [comment]
Why so long? You can screenshot the assembler area with this function and I can try to find in my version. Something should repeat.

**Comment by Ceiridge** [comment]
Because it takes so long to analyze the big binary and to open it. I'm not here to constantly help you. The patcher only supports the latest version and if you use an inferior older one, I can't and don't want to help you

**Comment by oleedd** [comment]
Then please just say the address of the first needed parameter (you have found it already) in the latest version you have.

**Comment by Ceiridge** [comment]
You can download the latest chrome.dll and patch it and the tool will print out the offset address in the console.
The patterns are in the patterns.xml file.
