### ISSUE TITLE
Please add Chrome Beta folders to Chrome.cs

### ISSUE THREAD

**Issue by CoolCmd** [Ceiridge/Chrome-Developer-Mode-Extension-Warning-Patcher#22]
`"C:\Program Files (x86)\Google\Chrome Beta\Application"`
`"C:\Program Files\Google\Chrome Beta\Application"`

---

And... why do you use `bck` file extension for backup copies? The standard file extension is `bak`.

**Comment by Ceiridge** [comment]
I use `.bck` extensions, because I like them more. `.bck` is also often used for backups.
7d9e00647614b34ca22db4cb9ac53206fcd02667
