### ISSUE TITLE
Please add Yandex Browser folder to InstallationFinder/Defaults

### ISSUE THREAD

**Issue by CoolCmd** [Ceiridge/Chrome-Developer-Mode-Extension-Warning-Patcher#23]
Yandex Browser: [https://browser.yandex.com/](https://browser.yandex.com/)
Folder: `C:\Users\*\AppData\Local\Yandex\YandexBrowser\Application\*.*.*.*\browser.dll`

i only tested the extension warning patch and it works. you can add this browser to `README.md`.

---

you can also remove Opera and Vivaldi from `README.md` because they do not need extension and urlbar patches (i do not know what other two patches do though).

**Comment by Ceiridge** [comment]
82faa85554a4d2d67f3957900fb2be7ede568d4e
