### ISSUE TITLE
[Feature request] Remove "Send to your devices"

### ISSUE THREAD

**Issue by Dibbyo456** [Ceiridge/Chrome-Developer-Mode-Extension-Warning-Patcher#24]
Previously we could remove it from Context Menu using the `Send tab to self` flag. But they removed the flag couple of versions back. I was hoping if you could somehow give us a patch to remove it.

![2020-06-18_19-21-08](https://user-images.githubusercontent.com/18257605/85028743-16de4700-b199-11ea-9dcb-9f3a6c48fc58.png)

**Comment by Ceiridge** [comment]
Which browser is this?

**Comment by Dibbyo456** [comment]
Google Chrome 83.0.4103.106 (Official Build) (64-bit)

**Comment by Ceiridge** [comment]
Have you tried this? https://www.guidingtech.com/disable-send-to-your-devices-chrome/

**Comment by Dibbyo456** [comment]
That will disable feature "Sync" of Open Tabs. I don't want to disable the feature itself just wants to remove the option from Context Menu. Previously this was possible using `Send tab to self` flag but the flag no longer available.

**Comment by Ceiridge** [comment]
https://source.chromium.org/chromium/chromium/src/+/master:chrome/browser/renderer_context_menu/render_view_context_menu.cc;l=1248;drc=fb6990704620473958c1b5c8a567d30ba048ab51;bpv=0;bpt=1?originalUrl=https:%2F%2Fcs.chromium.org%2F might be it

**Comment by Dibbyo456** [comment]
Yup, looks like it.

**Comment by Ceiridge** [comment]
c1f5e4a044b7df42804595c81e9aac233ebaae10

**Comment by Dibbyo456** [comment]
I tested the latest commit with Chrome Version 83.0.4103.116 (Official Build) (64-bit) and it worked!
Thank you so much for accepting the feature request. ❤

**Comment by Dibbyo456** [comment]
@Ceiridge This is broken as of version 4.1 :/
