### ISSUE TITLE
white windows

### ISSUE THREAD

**Issue by fabio1999ita** [Ceiridge/Chrome-Developer-Mode-Extension-Warning-Patcher#25]
hello, when i open program as administrator or also just a normal i can only see a white window
![Screenshot_1](https://user-images.githubusercontent.com/27001568/85404029-a485b200-b55e-11ea-817e-cbe229e4983b.png)

**Comment by Ceiridge** [comment]
How long did you wait after starting it? If nothing helps, you will need to use the command line: `ChromeDevExtWarningPatcher.exe --help`

**Comment by fabio1999ita** [comment]
i had wait like 5 minutes, i watch also process and it use 0 of cpu, i got last release of windows, can be this the problem?

![image](https://user-images.githubusercontent.com/27001568/85404986-0d215e80-b560-11ea-9da4-a9b886247221.png)

**Comment by Ceiridge** [comment]
I don't know how this is happening for you. The latest Windows update shouldn't be the problem. Have you tried killing the process and restarting it? Maybe your .NET installation is broken? Try installing the latest .NET Framework

**Comment by fabio1999ita** [comment]
program version:
![image](https://user-images.githubusercontent.com/27001568/85406293-dfd5b000-b561-11ea-88b2-85d3193fea77.png)

.net version:
![image](https://user-images.githubusercontent.com/27001568/85407198-3394c900-b563-11ea-9326-42a16ea2bee5.png)

this night i try to reinstall windowns10

**Comment by Ceiridge** [comment]
You can also just use the command line instead of the gui

**Comment by fabio1999ita** [comment]
whit a fresh windows it works thx
