### ISSUE TITLE
Stops working after shut down/restart

### ISSUE THREAD

**Issue by noodlychezzy** [Ceiridge/Chrome-Developer-Mode-Extension-Warning-Patcher#27]
I use this only to remove the developer warning, but every time I shut down, the patch stops working and the warnings appear again? Any way to stop this from happening
I've tried this on Brave and new edge

Thanks

**Comment by Ceiridge** [comment]
Does this always happen? Maybe there just was an update when you shut your PC down?
This shouldn't happen or does your drive always reset when restarting your pc?

**Comment by noodlychezzy** [comment]
Nope, no updates, though sometimes the warning starts appears after more than one restart.
My drive doesn't reset as far as I know, but I have Intel Optane if that makes a difference

**Comment by Ceiridge** [comment]
Okay, I can't tell you what causes this. I suggest you to add a scheduled task (with admin rights!) that starts the patcher with command line arguments.
https://github.com/Ceiridge/Chrome-Developer-Mode-Extension-Warning-Patcher#commandline-options
https://www.digitalcitizen.life/use-task-scheduler-launch-programs-without-uac-prompts

**Comment by noodlychezzy** [comment]
I'm not very good with this.
Does adding this to the end of "Target" in Properties patch Edge with the Warning patch?
` --customPath "C:\Program Files (x86)\Microsoft\Edge\Application" -w --groups 1`
If it does, could I just drag this into my start up folder, or would that pull up a UAC warning everytime I boot?

**Comment by noodlychezzy** [comment]
I can't really tell because the command prompt closes straight after it does its job when i open it

**Comment by Ceiridge** [comment]
To prevent a UAC warning, you should add it as a scheduled task with the Trigger **Logon** with your user account.
As an action, you should start it with these arguments: `ChromeDevExtWarningPatcher.exe -w --groups 0`. I think it should automatically find the browser. You can add more groups with commas.

Make sure that, when adding, you enable "start with highest privileges". 
You can find out how to add it in that blog article I sent earlier

**Comment by Ceiridge** [comment]
And you can remove the `-w` parameter to see the command prompt for 5 additional seconds

**Comment by noodlychezzy** [comment]
Thanks, does this mean its already patched
![image](https://user-images.githubusercontent.com/17392278/87162499-ed0ed080-c2bd-11ea-8115-c3cd6eb17d18.png)

**Comment by Ceiridge** [comment]
Yes and no:
Yes, because the `Debug Warning` is already patched, but no, because the group **1** is not the developer mode extension warning patch.
To remove that one, you need to use group **0**

**Comment by noodlychezzy** [comment]
Thanks

**Comment by noodlychezzy** [comment]
Thank you, I've got it working now

**Comment by iamthekings5** [comment]
Hi, I am encountering this issue as well. I have tried using TaskScheduler to rectify the issue to no avail.

**Comment by Ceiridge** [comment]
@iamthekings5 What's your issue? This has been solved already. This shouldn't be happening

**Comment by iamthekings5** [comment]
I'm on the latest version, on start-up it says the patch is outdated and needs to be patched again. But even if I patch it again the same error occurs. Edge was not updated.

Tried using TaskScheduler and command line arguments, same issue happens.

**Comment by Ceiridge** [comment]
> I'm on the latest version, on start-up it says the patch is outdated and needs to be patched again. But even if I patch it again the same error occurs. Edge was not updated.
> 
> Tried using TaskScheduler and command line arguments, same issue happens.

Make sure you select the browser

**Comment by iamthekings5** [comment]
I think it has something to do with how quickly you open your browser. Since the patch takes some time to apply and is not instantaneous, if you open it too quickly the warning would still show. I have Edge open on start-up sometimes so I still see the warning. But strangely this was not the case in the past, and you would only need to patch every time Edge was updated. Is this consistent with how the program works?

**Comment by Ceiridge** [comment]
> I think it has something to do with how quickly you open your browser. Since the patch takes some time to apply and is not instantaneous, if you open it too quickly the warning would still show. I have Edge open on start-up sometimes so I still see the warning. But strangely this was not the case in the past, and you would only need to patch every time Edge was updated. Is this consistent with how the program works?

Yes, now an injector runs on user startup, so you need to wait a bit until it initializes before you can start Edge (maybe some seconds?). Or did you log in with another user? 
Try closing and opening Edge again and tell me how often it doesn't patch

**Comment by iamthekings5** [comment]
> > I think it has something to do with how quickly you open your browser. Since the patch takes some time to apply and is not instantaneous, if you open it too quickly the warning would still show. I have Edge open on start-up sometimes so I still see the warning. But strangely this was not the case in the past, and you would only need to patch every time Edge was updated. Is this consistent with how the program works?
> 
> Yes, now an injector runs on user startup, so you need to wait a bit until it initializes before you can start Edge (maybe some seconds?). Or did you log in with another user?
> Try closing and opening Edge again and tell me how often it doesn't patch

Do you think it would be feasible to reintroduce the old method back (manual)? That way users can choose if they want Edge to run on start-up and still remove the extension warning.

Presently if I let Edge run on start-up it never patches, the warning always shows.

**Comment by Ceiridge** [comment]
> > > I think it has something to do with how quickly you open your browser. Since the patch takes some time to apply and is not instantaneous, if you open it too quickly the warning would still show. I have Edge open on start-up sometimes so I still see the warning. But strangely this was not the case in the past, and you would only need to patch every time Edge was updated. Is this consistent with how the program works?
> > 
> > 
> > Yes, now an injector runs on user startup, so you need to wait a bit until it initializes before you can start Edge (maybe some seconds?). Or did you log in with another user?
> > Try closing and opening Edge again and tell me how often it doesn't patch
> 
> Do you think it would be feasible to reintroduce the old method back (manual)? That way users can choose if they want Edge to run on start-up and still remove the extension warning.
> 
> Presently if I let Edge run on start-up it never patches, the warning always shows.

You can use a version older than 4.0, but I don't recommend it. Just don't put Edge into your startup

**Comment by iamthekings5** [comment]
> > > > I think it has something to do with how quickly you open your browser. Since the patch takes some time to apply and is not instantaneous, if you open it too quickly the warning would still show. I have Edge open on start-up sometimes so I still see the warning. But strangely this was not the case in the past, and you would only need to patch every time Edge was updated. Is this consistent with how the program works?
> > > 
> > > 
> > > Yes, now an injector runs on user startup, so you need to wait a bit until it initializes before you can start Edge (maybe some seconds?). Or did you log in with another user?
> > > Try closing and opening Edge again and tell me how often it doesn't patch
> > 
> > 
> > Do you think it would be feasible to reintroduce the old method back (manual)? That way users can choose if they want Edge to run on start-up and still remove the extension warning.
> > Presently if I let Edge run on start-up it never patches, the warning always shows.
> 
> You can use a version older than 4.0, but I don't recommend it. Just don't put Edge into your startup

The older versions aren't usable because they force you to update.

**Comment by Ceiridge** [comment]
> > > > > I think it has something to do with how quickly you open your browser. Since the patch takes some time to apply and is not instantaneous, if you open it too quickly the warning would still show. I have Edge open on start-up sometimes so I still see the warning. But strangely this was not the case in the past, and you would only need to patch every time Edge was updated. Is this consistent with how the program works?
> > > > 
> > > > 
> > > > Yes, now an injector runs on user startup, so you need to wait a bit until it initializes before you can start Edge (maybe some seconds?). Or did you log in with another user?
> > > > Try closing and opening Edge again and tell me how often it doesn't patch
> > > 
> > > 
> > > Do you think it would be feasible to reintroduce the old method back (manual)? That way users can choose if they want Edge to run on start-up and still remove the extension warning.
> > > Presently if I let Edge run on start-up it never patches, the warning always shows.
> > 
> > 
> > You can use a version older than 4.0, but I don't recommend it. Just don't put Edge into your startup
> 
> The older versions aren't usable because they force you to update.

You seem to be using an old version, which is not supported anymore. Please use the latest version in **Releases**.
When does Edge not get patched? How long is the system still running until then? Your problem isn't reproducible, so I can't fix it.
