### ISSUE TITLE
Not working on Edge (84.0.522.40)

### ISSUE THREAD

**Issue by rh63** [Ceiridge/Chrome-Developer-Mode-Extension-Warning-Patcher#29]
Hi Ceiridge,

title says it all, unfortunately...

Here's the log:
```
Patcher gui initialized
Searching for Chromium installations...
Added Chromium installation at C:\Program Files (x86)\Microsoft\Edge\Application\84.0.522.40\msedge.dll
Patching C:\Program Files (x86)\Microsoft\Edge\Application\84.0.522.40\msedge.dll...
Backupped to C:\Program Files (x86)\Microsoft\Edge\Application\84.0.522.40\msedge.dll.bck
Found pattern offset at 5499878
Source byte of patch at 22: 137
Source byte of patch at 18: 4
5499896 => 255
Found pattern offset at 5499878
Source byte of patch at 35: 72
Source byte of patch at 31: 8
5499909 => 255
Couldn't find offset for a patch Remove Debug Warning
Couldn't find offset for a patch Remove Elision
Error trying to patch C:\Program Files (x86)\Microsoft\Edge\Application\84.0.522.40\msedge.dll
```
Again, thanks for this tool, which make some of chromium's offsprings usable again!

**Comment by Ceiridge** [comment]
The patterns for _Remove Debug Warning_ and _Remove Elision_ don't seem to work at the moment for Edge. Disable these features for now. It's really annoying to keep the patterns up to date with almost every new browser update. Injecting a DLL on every Chromium start would be a good solution, but harder to implement

**Comment by rh63** [comment]
Thanks for the info. Will be patient until you find a solution... ;)

**Comment by Darthagnon** [comment]
Wondering, did the elision patch ever do anything on Edgium? I'm on Edgium Dev 85.0.564.8  and I've only noticed ```http://``` get hidden; ```https://``` and ```www``` have always show afaik?

**Comment by Ceiridge** [comment]
I don't use Edge, but on Chrome it makes `http://`, `https://` and `www` visible again

**Comment by Darthagnon** [comment]
I saw this [GHacks article](https://www.ghacks.net/2020/07/17/microsoft-hides-www-and-https-in-edge-canary-address-bar-then-restores-it/), which is very recent, and suggests M$ is experimenting with elision, and whether to leave it in (from Chromium source) or remove it. Sorta explains why I hadn't noticed it occurring yet, and other users (e.g. targeted testing? Edgium Canary users?) may have.

**Comment by ashunicorn** [comment]
Hi I tried the 4.0 release but Edge crashes every time when I applied remove extension warning. The version is the same as OP, 84.0.522.40. Does anyone have the same problem?

**Comment by rh63** [comment]
Can confirm **ashunicorn**'s problem. There's a brief 'flashing' attempt to create Edge's window, but that's it. No browser.

'Funny' enough, btw: on a fresh Edge installation (still v84.0.522.40) 3.9.2 does not work anymore either. Even when only '_Remove extension warning_' is selected for patching. This is the result:

`Couldn't find offset for a patch Remove Extension Warning`

But this is not a problem, since I just copied an already patched dll from another PC to that installation.

**Comment by DoctorPolski** [comment]
Can also confirm @ashunicorn's observation of a brief flash of a window outline then nothing.

**Comment by DoctorPolski** [comment]
A little more info on this.

Each time an attempt is made to open patched Edge the following system event warning entry is written:

> The application-specific permission settings do not grant Local Activation permission for the COM Server application with CLSID 
> {2593F8B9-4EAF-457C-B68A-50F6B8EA6B54}
>  and APPID 
> {15C20B67-12E7-4BB6-92BB-7AFF07997402}
>  to the user XXXXXXXXXX\xxxx SID (S-1-5-21-3990461154-2607866662-897530879-1001) from address LocalHost (Using LRPC) running in the application container Unavailable SID (Unavailable). This security permission can be modified using the Component Services administrative tool.

Also the scheduled task created by the patcher is configured for ```Windows Vista, Windows Server 2008``` rather than ```Windows 10```. I tried changing it to ```Windows 10``` but it made no difference so I'm reasonably sure this is not an issue, especially given the above.

**Comment by Ceiridge** [comment]
I haven't tried the patcher on Edge yet, because I was rushing the release, but I'm going to look into this soon

**Comment by DoctorPolski** [comment]
> I haven't tried the patcher on Edge yet, because I was rushing the release, but I'm going to look into this soon

Let me know if I can test anything.

**Comment by Ceiridge** [comment]
Fixed! https://github.com/Ceiridge/Chrome-Developer-Mode-Extension-Warning-Patcher/releases

**Comment by rh63** [comment]
Thanks a lot! Works perfectly now.
