### ISSUE TITLE
Brave Patcher

### ISSUE THREAD

**Issue by Ph0enixKM** [Ceiridge/Chrome-Developer-Mode-Extension-Warning-Patcher#3]
It's not an issue but rather a question. 
Is there any chance for a **Brave** patcher?

**Comment by Ceiridge** [comment]
Yes, Brave is also based on Chromium, so this patcher should also fully work with Brave, but the path of the Chrome installation is still hardcoded. I will make it possible later today to change it with a command line option, so every Chromium-based browser should be supported.

**Comment by Ceiridge** [comment]
https://github.com/Ceiridge/Chrome-Developer-Mode-Extension-Warning-Patcher/releases/tag/2.1

**Comment by Ph0enixKM** [comment]
Thanks a lot.
I recommend your patch as a solution to get rid of the warning box when my addon is installed with Dev Mode (on _Windows 10_ - rest of the OSes seem to not have such issue)

If you are curious about the addon:
https://github.com/Ph0enixKM/browser-zen-mode
