### ISSUE TITLE
Injector ignores some chrome instances (oplock race cond.)

### ISSUE THREAD

**Issue by RealBenDover** [Ceiridge/Chrome-Developer-Mode-Extension-Warning-Patcher#30]
Hi Ceridge,

unfortunately I've noticed that with Release 4.0 the patcher doesn't patch all chrome instances anymore. In my workflow I often rely on multitasking.  It happens more often that I have about 100 Chrome windows open. Unfortunately, the patcher often only takes care of some of them, not all. I am using the latest version of chrome.

I am curious if you find a solution!

**Comment by Dibbyo456** [comment]
@Ceiridge Can confirm the same issue.

**Comment by Ceiridge** [comment]
Fixed! https://github.com/Ceiridge/Chrome-Developer-Mode-Extension-Warning-Patcher/releases
