### ISSUE TITLE
Patcher doesn't work on windows 7 x86

### ISSUE THREAD

**Issue by RealBenDover** [Ceiridge/Chrome-Developer-Mode-Extension-Warning-Patcher#31]
Helo sir,
first of all thanks for the amazing patcher. My business computer is running windows 7 x86. The patcher doesn't work with chrome running on it. Hopefully you can do something about it. 
Appreciating your work!

**Comment by Ceiridge** [comment]
32-bit is not supported anymore. You can still try to use the old version

**Comment by RealBenDover** [comment]
Hi Ceirdge, please think again about investing a few minutes.  Many people still use 32 bit systems, especially in less developed countries.

**Comment by RealBenDover** [comment]
Ceridge, do you think you're better than the rest of us?  You probably live in a rich country where everyone can afford expensive 64 bits.  Our family can only afford 32 bits and we are again systematically discriminated against by you rich industrialized countries. Shame on you!

**Comment by Ceiridge** [comment]
Can you provide me with a screenshot of msinfo32, so I can check if your computer supports 64bit operating systems?
