### ISSUE TITLE
Chrome uses much more cpu and ram

### ISSUE THREAD

**Issue by Uranite** [Ceiridge/Chrome-Developer-Mode-Extension-Warning-Patcher#33]
yes
edit: lol what it now use the same ram and cpu lol

**Comment by Ceiridge** [comment]
So does everything work now with the latest version?

**Comment by Uranite** [comment]
yea, and it seems like it doesnt add more cpu and ram usage. but chrome will take more time to open maybe because this app needs to inject to chrome

**Comment by Ceiridge** [comment]
That's right, but it shouldn't take longer than 5 seconds on modern/usable computers
