### ISSUE TITLE
"Send to self" broken on v4.1

### ISSUE THREAD

**Issue by Dibbyo456** [Ceiridge/Chrome-Developer-Mode-Extension-Warning-Patcher#34]
Does not work with **v4.1** and Version 84.0.4147.89 (Official Build) (64-bit)

**Comment by Ceiridge** [comment]
Can you send me these log files:
`C:\Windows\Temp\ChromePatcherDll.log`
`C:\Windows\Temp\ChromePatcherDllErr.log`
and
`C:\Windows\Temp\ChromePatcherInjector.log`
`C:\Windows\Temp\ChromePatcherInjectorErr.log`

**Comment by wrd2093** [comment]
[ChromePatcherInjector.log](https://github.com/Ceiridge/Chrome-Developer-Mode-Extension-Warning-Patcher/files/4975490/ChromePatcherInjector.log)
[ChromePatcherInjectorErr.log](https://github.com/Ceiridge/Chrome-Developer-Mode-Extension-Warning-Patcher/files/4975491/ChromePatcherInjectorErr.log)
[ChromePatcherDll.log](https://github.com/Ceiridge/Chrome-Developer-Mode-Extension-Warning-Patcher/files/4975492/ChromePatcherDll.log)
[ChromePatcherDllErr.log](https://github.com/Ceiridge/Chrome-Developer-Mode-Extension-Warning-Patcher/files/4975493/ChromePatcherDllErr.log)

**Comment by Dibbyo456** [comment]
> Can you send me these log files

[logs.zip](https://github.com/Ceiridge/Chrome-Developer-Mode-Extension-Warning-Patcher/files/4975517/logs.zip)

**Comment by Ceiridge** [comment]
Can you also provide me with a screenshot of it not working? Like where do you see the "Send to device" option?

**Comment by Dibbyo456** [comment]
http://put.nu/files/w2XpR4O.png

**Comment by Ceiridge** [comment]
@Dibbyo456 Can you download *Process Hacker*, then open the parent main chrome.exe process properties > Memory > scroll down until you find an entry like this one: `Image - 133.228 kB (about 100 MB) - WCX - ...chrome.dll` > Right click > Save and send me that file?
Make sure that the injector is running and that you've installed it correctly

**Comment by Dibbyo456** [comment]
0x7ffef4d50000, Image, 133,228 kB, WCX, C:\Program Files (x86)\Google\Chrome\Application\84.0.4147.89\chrome.dll, 97,900 kB, 560 kB, 97,340 kB, 97,340 kB, 

http://put.nu/files/XRT5hSZ.zip

**Comment by Ceiridge** [comment]
da8e979e8c1db09f84f827158c66783726b4abe0
Please tell me if it works

**Comment by Dibbyo456** [comment]
Yes, it worked. Thank you so much.
