### ISSUE TITLE
Developer extension warning not disabled with 4.1.0.0 for Edge

### ISSUE THREAD

**Issue by wrd2093** [Ceiridge/Chrome-Developer-Mode-Extension-Warning-Patcher#35]
Using Microsoft Edge Version 84.0.522.44 (Official build) (64-bit) - the warning is now showing even after patching.

**Comment by Ceiridge** [comment]
Can you send me these log files:
`C:\Windows\Temp\ChromePatcherDll.log`
`C:\Windows\Temp\ChromePatcherDllErr.log`
and
`C:\Windows\Temp\ChromePatcherInjector.log`
`C:\Windows\Temp\ChromePatcherInjectorErr.log`

**Comment by Ceiridge** [comment]
@wrd2093 You sent your log files into the wrong issue, but I can't reproduce your problem anyway.

**Comment by wrd2093** [comment]
ok thanks

**Comment by Ceiridge** [comment]
That's right. I don't know, why it's not working for you, because I can't reproduce it. Maybe you should try to add the Edge installation manually in the patcher gui.
