### ISSUE TITLE
Enhancement, option to skip taskservice install

### ISSUE THREAD

**Issue by kababoom** [Ceiridge/Chrome-Developer-Mode-Extension-Warning-Patcher#37]
I just need the simple commandline patcher without any further registry and task services.
Uninstall is also not needed since a simple chrome reinstall/update would remove the patches.

Cheers,
-M

**Comment by Ceiridge** [comment]
The new patcher uses a scheduled task to inject the patcher dll into the Chrome processes. The old method had problems with Widevine and other things, so it's not supported anymore. You can still find a downloadable release, but it might not work anymore.
Alternatively, you can try to do it yourself somehow with the `patterns.xml`
