### ISSUE TITLE
Has slowed down Chromium Edge 

### ISSUE THREAD

**Issue by jha-vineet69** [Ceiridge/Chrome-Developer-Mode-Extension-Warning-Patcher#38]
It used to work fine but now since the new patch, edge takes a longer time to get up and running. 
Version 84.0.522.48 (Official build) (64-bit)
Also in the newer versions of Patcher, I see some extra files like TaskScheduler.dll and CommandLine.dll. Are those the ones slowing it down? Is there any other way or bypass or something to make the launch time faster again.

**Comment by Ceiridge** [comment]
No, every time Chrome starts, the patcher injects a dll that scans through the memory section of the _chrome.dll_ module. Because it's about 150MB big, it takes about 5 seconds per start. Launch times may vary when using a slower cpu
