### ISSUE TITLE
Question/Issue - 32-bit Chrome Version

### ISSUE THREAD

**Issue by T200proX7** [Ceiridge/Chrome-Developer-Mode-Extension-Warning-Patcher#4]
Hello,

i tried to use the Patcher. On V79 64-bit it worked fine. But it seems its not working for 32-bit, am i right its not supported - or am i doing something wrong?

regards

**Comment by Ceiridge** [comment]
Apparently it's not supported, because the signatures are different for 32bit/64bit. Maybe I will find and add the signatures for the 32bit version in the future.

**Comment by T200proX7** [comment]
That would be cool. By the way. Very great job. How did you find the necessary bytes for replacing?

**Comment by Ceiridge** [comment]
I searched in the Chromium source code for functions that I can patch to disable certain features and then I disassembled chrome.dll statically and debugged it with x64dbg to find them (which can take ages). Then I created a signature and patched the bytes. You can find more info in the README

**Comment by T200proX7** [comment]
You are crazy. Its admirable, the skills you have - and that you did it. I need to test it.. just to see what kind of things you faced.

**Comment by Ceiridge** [comment]
fa5110e38643663ab5e00531e637c54610dfabe7
