### ISSUE TITLE
Your DLL is triggering Anticheats

### ISSUE THREAD

**Issue by PrincessAkira** [Ceiridge/Chrome-Developer-Mode-Extension-Warning-Patcher#40]
Yoyo,
i found out your autopatch dll may be triggering anticheat and got me actually banned from Warframe and BattleEye Blocked
![image](https://user-images.githubusercontent.com/45071533/89027460-d68eee80-d32a-11ea-8a5b-84f8386132f7.png)

**Comment by Ceiridge** [comment]
I'm aware that the Windows hook injects the dll into every process with the same session, so also games and I also had the fear of this happening. I was sure that these anticheats would just block the dlls (like here) and then wouldn't care about it anymore.
Are you sure you were actually banned (maybe try uninstalling the patcher for now)?

**Comment by PrincessAkira** [comment]
ye i got banned twice in warframe after using new autoinject update 
![image](https://user-images.githubusercontent.com/45071533/89033709-b44f9d80-d337-11ea-8946-5ae668d8184b.png)
![image](https://user-images.githubusercontent.com/45071533/89033719-bade1500-d337-11ea-91f5-e75fb2076377.png)
![image](https://user-images.githubusercontent.com/45071533/89033743-ca5d5e00-d337-11ea-998f-c02f0dd805e4.png)

**Comment by PrincessAkira** [comment]
i literally got banned 20 minutes after i got unbanned.
I played, logged off after 20mins, logged back in 5 mins later and was beaned again

**Comment by Ceiridge** [comment]
Did they know that it was a false ban? Have you uninstalled it now, so you don't get banned again?

**Comment by PrincessAkira** [comment]
They know its a false ban. They unbanned me and then i got banned again

**Comment by Ceiridge** [comment]
Okay, I hope you'll get unbanned again. You should wait until the next release (4.4) before using the patcher again

**Comment by insulter69** [comment]
@PrincessAkira LOL XDDD YOUR ALT IS GONE FOREVER! that would make me so upset! But at least you can still play in 20 years. Or you just buy it again^^ xddd

**Comment by PrincessAkira** [comment]
My Alt?
I wish thats my MAIN XD

**Comment by Ceiridge** [comment]
I have found a new great method that doesn't require a running injector and only affects Chromium browsers, while still allowing Widevine to run. This means that the next release will be completely safe (again)

**Comment by PrincessAkira** [comment]
any eta?

**Comment by Ceiridge** [comment]
This should take some days, because it's a big change again and I need to wait for the coder of PeNet to fix their library, which should support my method of injection

**Comment by Ceiridge** [comment]
https://github.com/Ceiridge/Chrome-Developer-Mode-Extension-Warning-Patcher/releases
82d50a7c1da4a64250b02b3d4dd1aa67f0cf9d0a
