### ISSUE TITLE
Getting outdated patch warning everytime

### ISSUE THREAD

**Issue by Dibbyo456** [Ceiridge/Chrome-Developer-Mode-Extension-Warning-Patcher#41]
Even on the latest version.

![](http://put.nu/files/z6GvUDb.png)

**Comment by Ceiridge** [comment]
Have you tried clicking on _Install_ in the patcher gui?

**Comment by Dibbyo456** [comment]
Yes, I did. The patcher works. But everytime I open Chrome this pops up.

**Comment by Ceiridge** [comment]
You need to reinstall it every time Chrome updates? Are you sure you did that?

**Comment by Dibbyo456** [comment]
Ah. Sorry.
