### ISSUE TITLE
[Enhancement suggestion] Disable Chrome updates

### ISSUE THREAD

**Issue by Senliast** [Ceiridge/Chrome-Developer-Mode-Extension-Warning-Patcher#42]
Would it be possible to implement a feature, to fully disable Chrome auto-updates and the pop-up,
saying the browser is not up-to-date? That would be really great.

**Comment by Ceiridge** [comment]
It would be possible, but this won't be added.
You can probably disable the Chrome Updater by revoking _Full Access_ from SYSTEM, Administrators and your own user and others for this folder: `C:\Program Files (x86)\Google\Update` (might be different on your system).

**Comment by Senliast** [comment]
Yeah, i already did it, and the Chrome didn't auto-updated anymore, but then it brings often the pop-up that it is not up-to-date. So, it cannot auto-update anymore, but it still checks for updates, and brings the pop-up all the time. I also tried to found out to which web-sites it connects to check for updates and then block it with firewall but, unfortunately, without luck.

**Comment by Ceiridge** [comment]
Why don't you want to update Chrome? Can you send me a screenshot of the popup?

**Comment by WybeBosch** [comment]
Some people install this to not get a notification from chrome that they are running an extension in developer mode. Having a new notification saying "Are you sure you want to use it while chrome is outdated" Kind of defeats the point of not wanting to have a notification.

**Comment by Senliast** [comment]
Yeah, sure. I found this screenshot on the internet, its not from me, because it always takes one or two days, before it starts to show, but believe me, every time i tried to prevent Chrome updates, this pop-up comes earlier or later. And i want to disable the updates, because your patch gets deleted after Chrome update, and i must reinstall it, and i don't want it.

See:
https://superuser.com/questions/1256587/hide-chrome-update-notification
https://imgur.com/a/lnLLos0

There are also Chrome Admin Tools, these are downloadable Windows Group Policies and they allow to disable auto-updates
but, unfortunately, they only work in enterprise environments (and Chrome really checks, if the PC is in a domain!, if not -
it just doesn't take effect).

**Comment by Ceiridge** [comment]
You can set up the patcher install with the command line and schedule it with the Task Scheduler on logon or similar, so it always is reinstalled after logging on. I don't want to support using old Chrome versions and the _pattern.xml_ only guarantees support for the latest Chrome version.
Besides that, the current patcher and newer versions (that won't interfere with anticheats anymore) doesn't stop working on newer versions, but it's advised to reinstall it to make sure that the patterns are up to date.
