### ISSUE TITLE
Patcher 4.4 works perfectly but didn't work for 'Sandboxed' chrome

### ISSUE THREAD

**Issue by GrennKren** [Ceiridge/Chrome-Developer-Mode-Extension-Warning-Patcher#43]
This used to works normally in **4.3** and below version, but now when I already have patched the **Chrome** with the new one , notification warning extensions in **sandboxed Chrome**  still appearing out but not in **normal/unsandboxed chrome**.

I preferred sandboxing my chrome with **Sandboxie** and that notifications kinda annoying, that's why I used this patcher. Since previous version still working, I'll just keep using that.

**Comment by Ceiridge** [comment]
Okay, the Chrome patcher doesn't support strange environments like Sandboxie, old Chrome versions or 32bit versions. I don't recommend using old patcher versions, because the versions 4.0-4.3 inject the dll in every process it can (Windows hook behavior) and this triggers some anticheats.
