### ISSUE TITLE
Injector crashes on Windows 7

### ISSUE THREAD

**Issue by TirOFlanc** [Ceiridge/Chrome-Developer-Mode-Extension-Warning-Patcher#44]
Hi,

I have an issue with the lastest release, i put the screenshot in attach file, tell if you need more informations.

I don't have use command line, just the soft UI.

Have a nice day.

![Chromium patcher issue](https://user-images.githubusercontent.com/56934692/90787374-f2bbf500-e304-11ea-959d-26e3a0f0b508.PNG)

**Comment by Ceiridge** [comment]
What happens when you manually open the injector executable?

**Comment by TirOFlanc** [comment]
![Chromium patcher issue 2](https://user-images.githubusercontent.com/56934692/90789251-fcdef300-e306-11ea-84dd-6e33027b0f03.PNG)

**Comment by Ceiridge** [comment]
I have also experienced this issue in a Windows 7 VM and it's due to the ETW library I use. I'm not sure how to fix it, so that could take a while

**Comment by TirOFlanc** [comment]
Ok, I'll be patient. :)

**Comment by Ceiridge** [comment]
Can you try replacing the `KernelTraceControl.dll` file in `C:\Program Files\Ceiridge\ChromeDllInjector\amd64` with the attached files and test if one of them works and if not, try deleting the file entirely in that folder.
[DLLs.zip](https://github.com/Ceiridge/Chrome-Developer-Mode-Extension-Warning-Patcher/files/5104195/DLLs.zip)

**Comment by TirOFlanc** [comment]
Re

First dll file : same result
Second file : new error message

"Unable to start the program because api-ms-win-core-com-l1-1-0.dll is missing on your computer. Try reinstalling the program to fix this problem."

![Chromium patcher issue 3](https://user-images.githubusercontent.com/56934692/90808524-70d9c500-e320-11ea-94bc-58bcf26cceaa.PNG)

Third (without file) : same as First

**Comment by Ceiridge** [comment]
Can you also try this custom built version? Extract it where your current injector is and please try it:
[ChromeDllInjector.zip](https://github.com/Ceiridge/Chrome-Developer-Mode-Extension-Warning-Patcher/files/5105621/ChromeDllInjector.zip)

**Comment by Ceiridge** [comment]
Fixed: f8a2e06ed6888198ec0ae2841dec6c6d94983e0b
