### ISSUE TITLE
Outdated patterns for Brave 85

### ISSUE THREAD

**Issue by Ceiridge** [Ceiridge/Chrome-Developer-Mode-Extension-Warning-Patcher#45]
Chromium (probably works on no browser based on Chromium anymore):
- Fixed

Chrome:
- Chromium issues (Fixed)

Edge:
- Chromium issues (Fixed)

Brave:
- Debug Warning Patch
- Elision Patch

**Comment by Ceiridge** [comment]
0c16884076ab3f207018cea65284a52a6708adb0

**Comment by Ceiridge** [comment]
There might still be some issues for Edge or Brave when their update rolls out

**Comment by phly95** [comment]
Yup, new edge is giving an "out of date pattern" warning now.

**Comment by Ceiridge** [comment]
> Yup, new edge is giving an "out of date pattern" warning now.
> 
> Maybe it would be good to have the option to have it avoid bothering the user when an update happens. Basically, when it starts, if the patterns are out of date, it will check for updates. If none are available, it will silently run anyway, and automatically drop a github issue if one isn't already created. (of course, auto-dismissing the error could be an opt-in setting in the installation options)

It's a good idea, but not worth implementing. The warning that you are getting only indicates that the loaded browser dll is newer than the one while you installed the patcher. You can always get rid of the warning by reinstalling the patcher, although this only fixes new patterns when they are updated in the patterns.xml file while the patcher is being reinstalled.
It would also be too much effort to add an auto-update or similar to the patcher dll and would increase loading times even more.

**Comment by Ceiridge** [comment]
Additionally, I want the error to appear to notify the users and to prevent malicious usage.

**Comment by ericpa06** [comment]
> good idea, but not worth implementing
I totally disagree, at least this option should exist. Otherwise, you're just replacing the annoying **"disable developer mode extensions warning"** messages with other annoying warning message. which make the whole program pointless.

**Comment by phly95** [comment]
BTW, Edge updates very frequently. It's already been twice this week that I had to apply the patcher to get rid of the warning. Maybe Chrome doesn't get updated that frequently, so maybe the warnings are less of an issue on that browser.

**Comment by Ceiridge** [comment]
> > good idea, but not worth implementing
> 
> I totally disagree, at least this option should exist. Otherwise, you're just replacing the annoying **"disable developer mode extensions warning"** messages with other annoying warning message. which make the whole program pointless.

This makes sense.
I've now added an automated 1s timeout to the warning and removed its sound. It's now only a short visual annoyance at most or do you think it's still too annoying?

85265b41b29708f343e0705b740e171c800d4348
https://github.com/Ceiridge/Chrome-Developer-Mode-Extension-Warning-Patcher/releases

Besides that, the original issue here still isn't fully fixed for Brave, as I'm hoping for it to behave equally with Chromium 86.

**Comment by c0bnut** [comment]
> > > good idea, but not worth implementing
> > 
> > 
> > I totally disagree, at least this option should exist. Otherwise, you're just replacing the annoying **"disable developer mode extensions warning"** messages with other annoying warning message. which make the whole program pointless.
> 
> This makes sense.
> I've now added an automated 1s timeout to the warning and removed its sound. It's now only a short visual annoyance at most or do you think it's still too annoying?
> 
> [85265b4](https://github.com/Ceiridge/Chrome-Developer-Mode-Extension-Warning-Patcher/commit/85265b41b29708f343e0705b740e171c800d4348)
> https://github.com/Ceiridge/Chrome-Developer-Mode-Extension-Warning-Patcher/releases
> 
> Besides that, the original issue here still isn't fully fixed for Brave, as I'm hoping for it to behave equally with Chromium 86.
I personally think it's still too annoying. I would prefer an option to make it completely silent, Edge user here.

**Comment by Darthagnon** [comment]
Edge user here, too - Silent would be appreciated, too.

**Comment by Ceiridge** [comment]
I think I can actually remove the message box, because the user finds out if the version is outdated by seeing that the patches don't work anymore.
b6552bdd9b4b1bba2ad76de094e19892c266e599
https://github.com/Ceiridge/Chrome-Developer-Mode-Extension-Warning-Patcher/releases

**Comment by Darthagnon** [comment]
Much better! Thank you! Fits in with its primary purpose better, now, too, which is to get rid of annoying message boxes :D

**Comment by Seantourage** [comment]
Wanted to thank you so much for this patcher. Removes so many of the annoyances for us power users

**Comment by Ceiridge** [comment]
Issue continued here: https://github.com/Ceiridge/Chrome-Developer-Mode-Extension-Warning-Patcher/issues/60
