### ISSUE TITLE
Brave 85 no longer needs patching ?

### ISSUE THREAD

**Issue by TirOFlanc** [Ceiridge/Chrome-Developer-Mode-Extension-Warning-Patcher#46]
Hi,

With the new version 85 of Brave, I uninstalled your tool and I even uninstalled Brave to reinstall it cleanly and it seems that there is no more need to patch against the notification box that warns of an extension in developer mode.

Is it a dream or ... an error ?

**Comment by Ceiridge** [comment]
It's a dream that came true apparently. Either it's a bug or the developers of Brave are actually reasonable.
Still, the debug warning and the Elision (hiding WWW + HTTPS) is still in Brave (but maybe you don't care about that?)
So expect the warning again in future versions maybe

**Comment by TirOFlanc** [comment]
Indeed, that's all I use with your tool.

But, let me dream, it's not a mistake, they are reasonable at Brave ! ^.^

I'm going to thank them for that on twitter so that they don't change anything. xD
