### ISSUE TITLE
Feature Request: support Chrome on macOS

### ISSUE THREAD

**Issue by Senliast** [Ceiridge/Chrome-Developer-Mode-Extension-Warning-Patcher#49]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Please add support for Chrome on macOS.

**Describe alternatives you've considered (optional)**

**Additional context (optional)**

**Define a name for your feature (optional)**
Ex.: Remove annoying thing patch

**Comment by Ceiridge** [comment]
MacOS won't be supported (in the future), because that would require completely different approaches of injection and double the amount of work to find the patterns
