### ISSUE TITLE
Doesn't work with Edge (Chromium)

### ISSUE THREAD

**Issue by dheeraj-chakilam** [Ceiridge/Chrome-Developer-Mode-Extension-Warning-Patcher#5]
I've tried the patcher with the new Chromium Edge and it wasn't able to find `msedge.dll` as the target dll file. I had to follow the steps outlined here to get it working:
https://stackoverflow.com/questions/59870767/disable-microsoft-edge-chromium-developer-mode-extensions-pop-up-at-startup

**Comment by Ceiridge** [comment]
I will look into this in the future (maybe in some days or weeks?).
Then there will probably be a patcher gui that automatically finds browsers.

**Comment by kababoom** [comment]
Fyi, it does (did) work with Edge, just use the path and rename the edge.dll to chrome.dll

But it does not work anymore since the 81 update of today, see other issue.

Cheers,
-M

**Comment by Ceiridge** [comment]
84f026d9836c04320084c15b4afb34479b0c8fe6
