### ISSUE TITLE
Dll injector removal/startup

### ISSUE THREAD

**Issue by Zeinayyy** [Ceiridge/Chrome-Developer-Mode-Extension-Warning-Patcher#50]
hey could you remove the injector pls?, or could you tell me how to disable them during startup?

**Comment by Ceiridge** [comment]
No, it is required to make the patcher work, as it injects a DLL into the Chromium process. You can remove it by clicking on "Uninstall All" in the gui or by deleting the scheduled task in `taskschd.msc` (Task Scheduler)
