### ISSUE TITLE
Bug Report: Not working on New Edge in Win10 20H2

### ISSUE THREAD

**Issue by rophel** [Ceiridge/Chrome-Developer-Mode-Extension-Warning-Patcher#52]
**Describe your problem in one sentence:**
Error:  An error occurred trying to fetch the new patterns.  The program has to exit, as no cached version of the file has been found.  The rest was aborted: Could not create SSL/TLS secure channel.

**Name the affected patch/problem (if available)**
4.5.2

**Your used browser**
Edge 87.0.664.75 

**Screenshots (optional)**

**Longer description (optional)**

**Additional information (optional)**
Running windows version 20H2 (Build 19052.746) which integrated Edge more fully into OS, wondering if that's the issue.

**Comment by Ceiridge** [comment]
That's not because of Edge, but apparently my patcher GUI can't reach the Github servers anymore. I'm looking into it now!

**Comment by Ceiridge** [comment]
It works again!
913947b0d07150fad94e836709a9dde9167213fa
https://github.com/Ceiridge/Chrome-Developer-Mode-Extension-Warning-Patcher/releases
