### ISSUE TITLE
Bug Report: Not Working Edge 88.0.705.74 

### ISSUE THREAD

**Issue by MrHollowWeen** [Ceiridge/Chrome-Developer-Mode-Extension-Warning-Patcher#54]
**Describe your problem in one sentence:**
Tried Command Line and Gui.  Verified that correct Edge install path.

**Name the affected patch/problem (if available)**
4.5.3

**Longer description (optional)**
Tried multiple times both with Edge open and closed.  Every time I restart edge, the developer mode extension popup appears.

**Comment by Ceiridge** [comment]
I have just reinstalled it and the problem doesn't occur for me on the same Edge version. Also, the GUI has more features than the command line, so using that won't help.
Can you ensure that the injector scheduled task is running and that you actually have entered the right installation path to Edge?

**Comment by MrHollowWeen** [comment]
Can you provide me your command line command and arguments?   Perhaps I've got mine wrong.

Here's what I used:
ChromeDevExtWarningPatcher.exe --"C:\Program Files (x86)\Microsoft\Edge\Application\88.0.705.74" --groups 0,1,2,3,4

Here's the output:
Error: No patchable browser files found!
Cleared ChromeExes registry
Extracted injector zip
Wrote patcher dll to C:\Program Files\Ceiridge\ChromeDllInjector\ChromePatcherDll_161411448h8.38774.dll
Created and started task
Patches installed!

**Comment by Ceiridge** [comment]
Yes, almost everything went wrong with your command line syntax and the output shows it, too: `Error: No patchable browser files found!`.
Just use the gui?

**Comment by Ceiridge** [comment]
A valid command line would be:
`ChromeDevExtWarningPatcher.exe --customPath "C:\Program Files (x86)\Microsoft\Edge\Application" --groups 0,1,2`, which does:
- Remove Extension Warning
- Remove Debug Warning
- Remove Elision

**Comment by MrHollowWeen** [comment]
Oh, yes...I figured there was a problem based on the output. I guess I couldn't figure out why the error considering that my statement looks just like yours. You can't tell from my post but those are 2 dashes in between customPath and groups. I'm assuming a single space after customPath and groups?  And I am correct in including the version number folder in my path, correct?

**Comment by Ceiridge** [comment]
Closing, because the problem seems to have been fixed?
