### ISSUE TITLE
Feature Request: Patch Chrome Secure Prefrences.

### ISSUE THREAD

**Issue by AJolly** [Ceiridge/Chrome-Developer-Mode-Extension-Warning-Patcher#59]
**Is your feature request related to a problem? Please describe.**
Chrome secure preferences feature makes it much harder to backup, restore, dual boot, or use extensions with a portable chrome version. 
It also makes recovery from HD crashes much harder, as it will wipe out your preferences if it detects an inconsistency. 

This is intended to protect a user from malware/adware changing browser preferences external from chrome.

**Describe the solution you'd like**
Would love for this to get patched out.  

**Describe alternatives you've considered (optional)**

**Additional context (optional)**

This is the most up to date, detailed info I've found about how the chrome secure preferences file works - https://www.cse.chalmers.se/~andrei/cans20.pdf
Associated code -https://github.com/Pica4x6/SecurePreferencesFile

Second summary: https://www.adlice.com/google-chrome-secure-preferences/

**Comment by Ceiridge** [comment]
This looks like a big think to disable, at least I wasn't able to find it quickly in the Chromium source code https://source.chromium.org/chromium/chromium (or maybe it is Chrome only?).
Somebody else could maybe find it and send me the source code location to patch it or even make a pull request.

**Comment by AJolly** [comment]
In chromium source, there are a few places we could patch:

I think the cleanest would be PrefHashCalculators Validation result test?
https://source.chromium.org/chromium/chromium/src/+/master:services/preferences/tracked/pref_hash_calculator.h;drc=db0bc5c31204c9c7ab2f131af6fe2cf193e08876;l=17

**Comment by tophf** [comment]
FWIW might be useful: https://kaimi.io/2015/04/google-chrome-and-secure-preferences/

**Comment by AJolly** [comment]
@tophf Thanks! I had not seen that link before.  

I did find this bit of code to regen the secure preferences - https://gist.github.com/jesboat/56545d728750db5b4ea638266c04fde2

Or this - https://github.com/Pica4x6/SecurePreferencesFile

**Comment by Ceiridge** [comment]
It looks like it would make more sense to run that script once to fix the Secure Preferences, so that if the patcher stops working at some point because of an update or similar, the settings wouldn't be reset.
Fixing the settings hashes permanently when switching the computer is much more reliable than a just-in-time patcher in this case

**Comment by AJolly** [comment]
If you patch it, you could patch it to always regenerate the correct hashes, That functionality already exists in the code, as it's used to migrate from one version to secure preferences to the another.

Unfortunately I haven't been able to get those external scripts to work.

I'd be happy to put up a $1000 bounty if someone does add this feature to  Chrome developer mode patcher.
