### ISSUE TITLE
Not working anymore on v81

### ISSUE THREAD

**Issue by kababoom** [Ceiridge/Chrome-Developer-Mode-Extension-Warning-Patcher#6]
First of all thanks for this great patcher, amazing work !!!.

v81 is out and developermode patch is not working anymore.
Version 81.0.4044.92 (Official Build) (64-bit)

Do we need a new signature?

Cheers,
-M

**Comment by Ceiridge** [comment]
Yes. The new one is `41 57 41 56 41 54 56 57 53 48 81 EC ? ? ? ? 49 89 CC 48 8B 05 ? ? ? ? 48 31 E0 48 89 84 24 ? ? ? ? 48 8D 4A ?`
It will be added in the next version

**Comment by kababoom** [comment]
Thanks, that's quick, will check first thing tomorrow ..

Any easy way to find these updated sigs myself?

Cheers,
-M

**Comment by Ceiridge** [comment]
It will be released in some minutes

**Comment by Ceiridge** [comment]
84f026d9836c04320084c15b4afb34479b0c8fe6

**Comment by kababoom** [comment]
Tested little later then planned but working again.
Awesome work .....

Cheers,
-M

**Comment by ivan** [comment]
The stable Edge release 81.0.416.53 (Official build) (64-bit) is failing to patch here, I tested fa5110e38643663ab5e00531e637c54610dfabe7
![patch error Annotation 2020-04-14 013726](https://user-images.githubusercontent.com/4458/79176766-a7db1f80-7df0-11ea-9833-1ba84e9e8a7f.png)

**Comment by Ceiridge** [comment]
Can you upload the dll file for me somewhere?

**Comment by Ceiridge** [comment]
And does the release 3.0 work for you instead?

**Comment by ivan** [comment]
It does not work with 3.0 either. I am uploading the .dll now and will link soon.

**Comment by ivan** [comment]
81.0.416.53 msedge.dll https://ludios.org/tmp/msedge.7z

**Comment by Ceiridge** [comment]
e569af7111d4028e398b700dab9974e7381a9b17
https://github.com/Ceiridge/Chrome-Developer-Mode-Extension-Warning-Patcher/releases/tag/3.2
