### ISSUE TITLE
Feature Request: Stop Chrome from updating

### ISSUE THREAD

**Issue by m0ck69** [Ceiridge/Chrome-Developer-Mode-Extension-Warning-Patcher#61]
I'm sorry for the off-topic but I couldn't find other way to contact you.

Can you make an app to stop Chrome from updating?
I googled it and tried everything.
Disable Google Services, deleting/renaming googleupdate.exe, changing registry keys etc and it all for nothing. 
I mean it seems to work for a short period of time but eventually Chrome updates nonetheless.
No matter what I do, Chrome will update in the background sooner or later.

It would be nice to have an app to disable Chrome from updating permanently.

**Comment by Ceiridge** [comment]
Maybe you should try this script if you want to permanently have an unsafe, inferior and unsupported version of Chrome: https://gist.github.com/absynce/7667bd32e632e72f406f

**Comment by m0ck69** [comment]
I use Firefox on a daily basis. I use Chrome only with certain extensions which only with old versions of Chrome like 86.xxx. 
So it's not unsafe. However, Chrome keeps constantly updating and ruins all extensions etc.
So disabling Chrome from updating permanentny does actually make sense If the browser is used just for the certain purposes.

I'll try this script that you provided but it's entirely based on registry keys so I'm pretty sure it won't work.

**Comment by Ceiridge** [comment]
You will need to paste that powershell script into a powershell console and then execute the function with `SetChromeUpdates false`

**Comment by Ceiridge** [comment]
This issue has probably been resolved
