### ISSUE TITLE
Feature Request: Remove "create qr code for this page" from the context menu

### ISSUE THREAD

**Issue by cpuuntery** [Ceiridge/Chrome-Developer-Mode-Extension-Warning-Patcher#62]
**Is your feature request related to a problem? Please describe.**

[![please-help.png](https://i.postimg.cc/Hk824VXL/please-help.png)](https://postimg.cc/fVZmMWH4)

In chrome 90 there was a flag to remove the annoying "create qr code for this page" from the context menu 
the flag is 

chrome://flags/#sharing-qr-code-generator

but it seems that the flag is going to be removed by version 92 or 93
I just hope before chrome remove the flag. This tool will be able to remove the annoying "create qr code for this page" from the context menu.
For now, to reach this flag you need to enable 
temporary-unexpire-flags-m89
temporary-unexpire-flags-m90
which means the flag is going to be removed and Deprecated

**Describe the solution you'd like**
I want to remove the annoying "create qr code for this page" from the context menu

**Comment by Ceiridge** [comment]
90f0dc22496b4fb9b0985d8c851b5db2e86d7ee2
