### ISSUE TITLE
The exe does not run/crashes very quickly

### ISSUE THREAD

**Issue by ArshZilpe** [Ceiridge/Chrome-Developer-Mode-Extension-Warning-Patcher#64]
Once I start the exe, it either does not run, or a window appears for 0.1 seconds then disappears. 

I have tried turning off all antivirus software and whitelisting it. I have also tried running it from the command line. I have also made sure to run as administrator, but it still does not run. What am I doing wrong? 

Thanks!

**Comment by Ceiridge** [comment]
Do you have the .NET 5 Desktop Runtime installed as stated in the README? https://dotnet.microsoft.com/download/dotnet/5.0/runtime

**Comment by ArshZilpe** [comment]
Yes, I do. I forgot to mention that. I cleanly reinstalled it as well.

**Comment by Ceiridge** [comment]
Is there any event in the Event Viewer regarding that and does the process also crash in the Task Manager?

**Comment by ArshZilpe** [comment]
Ah. I hadn't installed the desktop-runtime version. Thanks!
