### ISSUE TITLE
Unable to remove "Create QR code for this page" in chrome 92 

### ISSUE THREAD

**Issue by cpuuntery** [Ceiridge/Chrome-Developer-Mode-Extension-Warning-Patcher#65]
**Describe your problem in one sentence:**
Unable to remove "Create QR code for this page" in chrome 92

**Name the affected patch/problem (if available)**
Remove QR codes

**Your used browser**
92.0.4515.107

**Longer description (optional)**
The patch was working in version 91. I think it stopped working because 92 is a major version and a lot has changed in the code. so the memory address of the patch needs to be changed

**Comment by Ceiridge** [comment]
I will take a look at this issue in some days. I already saw your issue five days ago, but forgot about it until now

**Comment by Ceiridge** [comment]
Fixed: b51129551e3ce696be30bd7743e3585403f19157
