### ISSUE TITLE
Broken with New Edge version

### ISSUE THREAD

**Issue by waxamoto** [Ceiridge/Chrome-Developer-Mode-Extension-Warning-Patcher#7]
Hi! first of all I would like to thank you for the excellent patch, I am really sorry to bother you again, but it is not working with the newest MS Edge version 81.0.416.53 ..... thanks very much!

**Comment by Ceiridge** [comment]
e569af7111d4028e398b700dab9974e7381a9b17
https://github.com/Ceiridge/Chrome-Developer-Mode-Extension-Warning-Patcher/releases/tag/3.2
