### ISSUE TITLE
Help Needed

### ISSUE THREAD

**Issue by SubGi** [Ceiridge/Chrome-Developer-Mode-Extension-Warning-Patcher#71]
I want some external help.
I am tired of pasting this code in the console everytime to fix a chromium bug related to video playback speed. I am a total newbie so I can't write a tampermonkey script. What would be the equavalent code for this console script in tampermonkey?
v = document.querySelector('video');
setInterval(()=> {
	v.currentTime = v.currentTime;
}, 30000);

**Comment by Ceiridge** [comment]
I am not the Tampermonkey support.
