### ISSUE TITLE
Extension Warning Patcher causing crash on Edge

### ISSUE THREAD

**Issue by ZahNarztiK** [Ceiridge/Chrome-Developer-Mode-Extension-Warning-Patcher#73]
My PC: Windows 10 (64-bit)
Current Microsoft Edge Version 96.0.1054.29 (Official build) (64-bit)

Last night, previously, Patcher 5.1.0 and Edge (couldn’t recall which version) working just fine.
Timeline of problem:
- Edge updated (96.0.1054.29)
- Edge crashed on running. App suspended and closed.
- Edge repaired, not working.
- PC restarted, not working.
- Patch uninstalled, Edge working.
- Patcher updated (5.2.1), re-installed and tested, Edge not working again.
- Patch uninstalled, Edge working.

Please review this issue. 

Appreciated. :D

**Comment by thebigsmileXD** [comment]
Same here, but it appears disabling the Elision patch fixes it

**Comment by Ceiridge** [comment]
Fixed with: 02a7f524f082c4e9304832649b2d7bb5fa20a4df
An old Elision pattern now matched with some random code and because of that, it crashed.
Edge has removed Elision (which stands for the change that hides WWW and HTTPS in the url bar, like it is the case in Chrome or Brave) anyway.
