### ISSUE TITLE
Patcher not working on MS Edge

### ISSUE THREAD

**Issue by ZahNarztiK** [Ceiridge/Chrome-Developer-Mode-Extension-Warning-Patcher#78]
MS Edge was updated recently and the Extension Warning Patcher is no longer working.

Microsoft Edge, Version 100.0.1185.29 (Official build) (64-bit).

**Comment by Ceiridge** [comment]
Fixed by 2f8b5a6c77251846480be6c415dd0636043451cc

**Comment by ZahNarztiK** [comment]
Wow, so fast!
That resolves perfectly fine.

Thanks thousand times, [Ceiridge](https://github.com/Ceiridge)
