### ISSUE TITLE
Feature Request: Support Patching Unsupported Flag Ticker

### ISSUE THREAD

**Issue by aaronliu0130** [Ceiridge/Chrome-Developer-Mode-Extension-Warning-Patcher#79]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I start my browser and get the annoying ticker "You are using an unsupported command-line flag <insert flag here>. Stability and security will suffer." There are certain very useful flags that trigger this message, such as `--extensions-on-edge-urls` .

**Describe the solution you'd like**
Somehow patch this.

**Describe alternatives you've considered (optional)**
Remove the flag.

**Define a name for your feature (optional)**
Ex.: Add patch to remove unsupported flag ticker

**Comment by Ceiridge** [comment]
Try setting this policy/registry value to 0 first: https://chromeenterprise.google/policies/?policy=CommandLineFlagSecurityWarningsEnabled

**Comment by aaronliu0130** [comment]
I can't find the relevant policy key for edge.

**Comment by Ceiridge** [comment]
You will probably need to set it manually in the registry.
Maybe you can guess the registry path with the help of these resources:
https://admx.help/?Category=ChromeEnterprise&Policy=Google.Policies.Chrome::CommandLineFlagSecurityWarningsEnabled

**Comment by aaronliu0130** [comment]
There appears to be no HKLM\SOFTWARE\Policies\Microsoft\Edge keys

**Comment by Ceiridge** [comment]
Then create they registry key and try if it works.
HKLM means `HKEY_LOCAL_MACHINE`, maybe that's the issue?

**Comment by aaronliu0130** [comment]
Still doesn't work. Do I have to reboot or something?
![image](https://user-images.githubusercontent.com/11874211/163551770-728c2c58-9ad8-4bb1-82d6-136a48d95128.png)

**Comment by Ceiridge** [comment]
This policy normally should hide these warnings, but apparently it does not work (for Edge?).
I will add a patch soon

**Comment by aaronliu0130** [comment]
I'll say this again:
I'm using Micrsoft Edge, not chrome, and I can't find the key.
________________________________

**Comment by Ceiridge** [comment]
Adding the command line flag `--test-type` should work. Tell me if there are other consequences

**Comment by aaronliu0130** [comment]
Sorry for the mail 2 days ago, that should've been sent out much earlier on Apr 12. Anyways yes that does solve the problem, but it isn't very convenient since I usually launch my apps from the taskbar, and windows 11 appears to lack the functionality of pinning short cuts. why did I upgrade

**Comment by Ceiridge** [comment]
Are you sure that you cannot pin a shortcut to taskbar by right-clicking on it, selecting *Show more options* and then clicking on *Pin to taskbar*?

**Comment by aaronliu0130** [comment]
Ooh, yes I can. There's a minor problem though. Windows doesn't think shortcuts with/without parameters are different and wouldn't let me pin the shortcut with a parameter without removing the old one.

**Comment by Ceiridge** [comment]
I took a look at the Chromium source code responsible for this information bar and found out that there is a policy that is supposed to disable it. That was months ago. Apparently Chromium ignores the policy.
Luckily, there is a command line argument that fixes this somehow.
If there is a policy or similar, no patches are needed

**Comment by aaronliu0130** [comment]
I'd like to know: which policy?

**Comment by Ceiridge** [comment]
This one:
https://github.com/Ceiridge/Chrome-Developer-Mode-Extension-Warning-Patcher/issues/79#issuecomment-1094412397
Can be found here:
https://source.chromium.org/chromium/chromium/src/+/main:chrome/browser/ui/startup/infobar_utils.cc;l=37;drc=21a4c84dd469bfdc9f27375133dc309b62101ef8
