### ISSUE TITLE
Unable patch Edge version 81.0.416.53

### ISSUE THREAD

**Issue by dheeraj-chakilam** [Ceiridge/Chrome-Developer-Mode-Extension-Warning-Patcher#8]
After my edge updated to the latest version, the patcher doesn't work anymore.

![image](https://user-images.githubusercontent.com/20345157/79288365-82075680-7e94-11ea-842e-59dd5de9bafc.png)

**Comment by Ceiridge** [comment]
Have you also downloaded the latest version?

**Comment by Ceiridge** [comment]
Or did you already patch Edge or are you using the 32-bit version of Edge?

**Comment by dheeraj-chakilam** [comment]
Oops
