### ISSUE TITLE
Enable webRequestBlocking for MV3 not working in Chrome or Edge

### ISSUE THREAD

**Issue by dhprototype** [Ceiridge/Chrome-Developer-Mode-Extension-Warning-Patcher#86]
Chrome version 107.0.5304.107
Edge version 107.0.1418.56

DLL locations:
C:\Program Files\Google\Chrome\Application\107.0.5304.107\chrome.dll
C:\Program Files (x86)\Microsoft\Edge\Application\107.0.1418.56\msedge.dll

I am still getting following errors:
![image](https://user-images.githubusercontent.com/9678346/203614278-581c716c-c281-4a8a-ba3e-a0ced1dcb942.png)

Additional screenshots:
![image](https://user-images.githubusercontent.com/9678346/203615569-a14d9198-f6af-434e-b997-f5a624fa03f7.png)
![image](https://user-images.githubusercontent.com/9678346/203615554-24f372a6-f50f-4dc3-a385-17fa3f8de1a7.png)

**Comment by dhprototype** [comment]
Thank you for your response. Here are the log files from the temp folder.

[ChromePatcherDll.log](https://github.com/Ceiridge/Chrome-Developer-Mode-Extension-Warning-Patcher/files/10078189/ChromePatcherDll.log)
[ChromePatcherDllErr.log](https://github.com/Ceiridge/Chrome-Developer-Mode-Extension-Warning-Patcher/files/10078190/ChromePatcherDllErr.log)
[ChromePatcherInjector.log](https://github.com/Ceiridge/Chrome-Developer-Mode-Extension-Warning-Patcher/files/10078191/ChromePatcherInjector.log)

**Comment by blis5fool** [comment]
Hello. Thank you so much for the update.
Is there a specific step I should use to apply the patch?
It seems to work when I re-install the browser. I think got it working once without re-installation, but I can't seem to reproduce it. I was wondering if I'm missing something or if this is expected.

What I'm doing is:
1. Remove extension
2. Uninstall patch
3. Uninstall browser
4. Re-install browser
5. Re-install patch
6. Load unpacked extension

**Comment by Ceiridge** [comment]
The browser or extensions do not need to be reinstalled at all. As long as the patch is working, the patch just has to be installed and MV3 extensions should have access to the webRequestBlocking API.

**Comment by blis5fool** [comment]
Right. That's what I was expecting. But, for some reason, that is not the case for my environment. I will try in another environment and let you know.
