### ISSUE TITLE
Enable webRequestBlocking for MV3 not working in latest Chrome

### ISSUE THREAD

**Issue by knsoftoa** [Ceiridge/Chrome-Developer-Mode-Extension-Warning-Patcher#87]
The patcher stopped working after google chrome updated today.

C:\Program Files\Google\Chrome\Application\108.0.5359.72\chrome.dll 
Chrome version: Version 108.0.5359.72 (Official Build) (64-bit)

![image](https://user-images.githubusercontent.com/119634942/205175818-13c085c1-011a-4438-b78f-241c6cce8b85.png)

[ChromePatcherDll.log](https://github.com/Ceiridge/Chrome-Developer-Mode-Extension-Warning-Patcher/files/10136736/ChromePatcherDll.log)
[ChromePatcherDllErr.log](https://github.com/Ceiridge/Chrome-Developer-Mode-Extension-Warning-Patcher/files/10136737/ChromePatcherDllErr.log)
[ChromePatcherInjector.log](https://github.com/Ceiridge/Chrome-Developer-Mode-Extension-Warning-Patcher/files/10136738/ChromePatcherInjector.log)

I tried re-installing the patcher, as well as the browser.

**Comment by Ceiridge** [comment]
You should also stop reinstalling your browser. This will never help in regards to this patcher.

**Comment by knsoftoa** [comment]
I confirmed that the issue is fixed. Thank you!

**Comment by knsoftoa** [comment]
> You should also stop reinstalling your browser. This will never help in regards to this patcher.

noted, thanks!
