### ISSUE TITLE
Bug Report: Unable to run with .NET Runtime 6.0

### ISSUE THREAD

**Issue by bananakid** [Ceiridge/Chrome-Developer-Mode-Extension-Warning-Patcher#89]
**Describe your problem in one sentence:**
Patcher won't run if .NET Runtime 6.0 only is installed.

**Name the affected patch/problem (if available)**
All

**Your used browser**
Microsoft Edge 100.0.1185.50

**Longer description (optional)**
AIFAIK .NET Runtime 4.5+[provides backwards compatibility](https://learn.microsoft.com/en-us/dotnet/framework/migration-guide/version-compatibility). However patcher won't run if I have .NET Runtime 6.0 only. It succeeds to run only if specifically .NET Runtime 5.0 is installed. It would be nice if patcher worked with .NET Runtime 5.0+ as well.

**Comment by Ceiridge** [comment]
I can't easily make it self-contained, because it would require many changes regarding to the build process including the C++ dependencies.
I have upgraded all .NET subprojects to .NET 6, so that there is also no more .NET Framework in use with #90

**Comment by bananakid** [comment]
@Ceiridge, thanks for looking into it!
