### ISSUE TITLE
Commandline Options

### ISSUE THREAD

**Issue by TirOFlanc** [Ceiridge/Chrome-Developer-Mode-Extension-Warning-Patcher#9]
Hi,

First of all thank you for this great tool!

Is there a reason why the command line tool was removed?
Because it was very useful and it would be great to have it back!

Thank you very much.

**Comment by Ceiridge** [comment]
Yes, I was too lazy and it's a protection against malicious use (although it can be bypassed by just downloading this repo and changing the code)

**Comment by TirOFlanc** [comment]
Ok, and will it be back for the next versions because I don't know how to modify this code and compile it.

**Comment by Ceiridge** [comment]
They will probably be added back in some hours or days. I'm currently working on disabling the automatic gain control in WebRTC

**Comment by TirOFlanc** [comment]
Well, that's great then.
I'll be patient.
Good luck with your WebRTC research ;)

**Comment by Ceiridge** [comment]
29c0922d3ebd096f2cba619771d171d85a282480
https://github.com/Ceiridge/Chrome-Developer-Mode-Extension-Warning-Patcher/releases/tag/3.3

**Comment by TirOFlanc** [comment]
Nice !
Thank you.
