### ISSUE TITLE
Bug Report: Patcher wouldn't run

### ISSUE THREAD

**Issue by bolabola6789** [Ceiridge/Chrome-Developer-Mode-Extension-Warning-Patcher#93]
**Describe your problem in one sentence:**
Patcher wouldn't run even with .NET runtime 6 already installed

**Name the affected patch/problem (if available)**
All

**Your used browser**
Edge 109.0.1518.52 64-bit, Windows 11 build 25276 (dev)
**Screenshots (optional)**

**Longer description (optional)**
 When I tried to launch the .exe mentioned in README, UAC appeared and after clicking "Yes" a cmd window launched and crashed immediately 

**Additional information (optional)**
Add any other information about the problem here.

**Comment by Ceiridge** [comment]
- Have you installed the .NET 6 Desktop runtime?
- Please open event viewer (eventvwr) and under the *Applications* tab, search for errors regarding the patcher.

**Comment by bolabola6789** [comment]
Oops, I clicked on the link in README.md and accidentally downloaded the amd64 version under "Run console apps". I downloaded the correct edition under event viewer and it's working properly now.
