### ISSUE TITLE
Bug Report: "Enable webRequestBlocking extension API for Manifest V3 extensions" is not working

### ISSUE THREAD

**Issue by StiliyanHoody** [Ceiridge/Chrome-Developer-Mode-Extension-Warning-Patcher#94]
**Describe your problem in one sentence:**
"Enable webRequestBlocking extension API for Manifest V3 extensions" is not working in any browser.

**Name the affected patch/problem (if available)**
"Enable webRequestBlocking extension API for Manifest V3 extensions"

**Your used browser**
I tried every browser I know (google chrome, edge, brave, chromium (installed)) and I tried multiple portable versions from the web.
All of the versions I tried were 102+

**Comment by Ceiridge** [comment]
I will look into this in the next 1-12 weeks
